name: FFA
api: [4.0.0]
version: 1.0.0
main: Laith98Dev\FFA\Main
author: Laith98Dev

commands:
  ffa:
    description: FFA Commands
    permission: ffa.command.admin

permissions:
  ffa.command.admin:
    default: true
    description: Permission to allow use all ffa commands
