name: FFA
api: [4.0.0]
version: 1.0.2
main: Laith98Dev\FFA\Main
author: Laith98Dev
website: https://github.com/Laith98Dev

permissions:
  ffa.command.admin:
    default: op 
  ffa.command.join:
    default: true
  ffa.command.quit:
    default: true